[local]
localhost

 [mongodb]
 mongodb-dev.devops7.online


 [catalogue]
 catalogue-dev.devops7.online

 [redis]
 redis-dev.devops7.online

 [user]
 user-dev.devops7.online

 [cart]
 cart-dev.devops7.online

 [mysql]
 mysql-dev.devops7.online

 [shipping]
 shipping-dev.devops7.online

 [rabbitmq]
 rabbitmq-dev.devops7.online

 [payment]
 payment-dev.devops7.online

 [frontend]
 frontend-dev.devops7.online

