- name: app setup
  ansible.builtin.import-role:
    name: common
    tasksfrom: app-setup.yaml

- name: nodejs setup
  ansible.builtin.import-role:
    name: common
    tasksfrom: nodejs.-setup.yaml 

- name: systemd_setup
  ansible.builtin.import-role:
    name: common
    tasksfrom: systemd-setup.yaml   

- name: start user
  ansible.builtin.service:
  name: user
  state: restarted
  enabled: yes