- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: pyhton setup
  ansible.builtin.import_role:
    name: common
    tasks_from: pyhton.setup.yaml

- name: systemd_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml

- name: restart payment
  ansible.builtin.systemd_service:
    name: payment
    state: restarted