- name: message
  ansible.builtin.debug:
    msg: "chennai super kings"

- name: set the os fact
  ansible.builtin.set_fact:
    os: "debian"

- name: message
  ansible.builtin.debug:
    msg: "wicket keeper" 

- name: message
  ansible.builtin.debug:
    msg: "finisher"   