- name: message
  ansible.builtin.debug:
    msg: "chennai super kings"

- name: message
  ansible.builltin.debug:
    msg: "wicket keeper" 

- name: message
  ansible.builtin.debug:
    msg: "finisher"   